[build]
  # Base directory (where the project files are located)
  base = "project"
  
  # Build command - install function dependencies first
  command = "cd netlify/functions && npm install && cd ../.. && npm run build"
  
  # Directory to publish (Vite default output)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Enable CI mode
  CI = "true"
  # Netlify Functions environment variables
  JWT_SECRET = "your-jwt-secret-key-here"
  JWT_EXPIRES_IN = "7d"
  MONGODB_URI = "your-mongodb-connection-string"
  NODE_ENV = "production"
  # Frontend environment variables
  VITE_APP_NAME = "ModernApp"
  VITE_API_URL = "/.netlify/functions"
  VITE_NETLIFY_FUNCTIONS_URL = "/.netlify/functions"
  VITE_GOOGLE_ANALYTICS_ID = "G-XXXXXXXXXX"
  VITE_GOOGLE_FONTS_API_KEY = "your-google-fonts-api-key"
  VITE_UNSPLASH_ACCESS_KEY = "your-unsplash-access-key"

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Functions configuration
[functions]
  directory = "project/netlify/functions"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Comprehensive security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Basic security
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:; frame-ancestors 'none';"
    
    # HSTS (HTTP Strict Transport Security)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.{png,jpg,jpeg,gif,svg,webp,avif}"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Cache fonts
[[headers]]
  for = "*.{woff,woff2,ttf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Don't cache HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache manifest and service worker
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
