[build]
  # Base directory (where the project files are located)
  base = "project"
  
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite default output)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Enable CI mode
  CI = "true"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
