[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite default output)
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Enable TypeScript checking during build
  CI = "true"
  # Treat warnings as errors in production
  GENERATE_SOURCEMAP = "false"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://your-domain.com/*"
  to = "https://your-domain.com/:splat"
  status = 301
  force = true

# Optional: Redirect www to non-www (uncomment if needed)
# [[redirects]]
#   from = "https://www.your-domain.com/*"
#   to = "https://your-domain.com/:splat"
#   status = 301
#   force = true

# Form handling (if you have contact forms)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Development context (for branch deploys)
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Production context
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Optional: Enable Netlify Analytics
# [[plugins]]
#   package = "netlify-plugin-submit-sitemap"
#   
#   [plugins.inputs]
#     baseUrl = "https://your-domain.com"
#     sitemapPath = "/sitemap.xml"
#     providers = [
#       "google",
#       "bing"
#     ]
